### ISSUE TITLE
CNT-DNNs

### ISSUE THREAD

**Issue by ghost** [EmanueleLM/OREs#1]
Thank you for your excellent work about "Characterizing Learning Dynamics of Deep Neural Networks via Complex Networks". Mentioned in your article that the relevant code has been made public, but I not find your code in "https://github.com/EmanueleLM/CNT-DNNs"

**Comment by EmanueleLM** [comment]
Hi Buildernet, the code is now available (updates will be made to the repo, especially regarding updates on the
dependencies which now rely on older versions of tf/keras).
Unfortunately I've to close the issue as it is ot here (next time send me an email, you can find info on my github profile).

Best,
Emanuele
